# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: Features
      labels:
        - Semver-Minor
        - enhancement
    - title: Dependencies
      labels:
        - Semver-Minor
        - Semver-Patch
        - dependencies
    - title: Fixes
      labels:
        - Semver-Patch
        - bug
    - title: Other Changes
      labels:
        - "*"
