name: Pull Request Labeler

on:
  pull_request:

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Labels
        uses: action-runner/conventional-labeler@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the output
        run: echo "The labels were ${{ steps.label.outputs.labels }}"
